### ISSUE TITLE
Contao 4.6

### ISSUE THREAD

**Issue by dmolineus** [ctsmedia/docker-contao#6]
Thanks for sharing your docker setup here. Is it planned to support Contao 4.6 soon?

**Comment by DanielSchwiperich** [comment]
Hi @dmolineus, will try to find some time for it during the next days

**Comment by DanielSchwiperich** [comment]
I did update the docker images. A quick test with contao 4.6 did show no problems. Also the demo data works. 
Let me know if you encounter any issues. 
contoa-manager was also auto updated in all new releases to 1.0.4

I also updated the previous versions:

- 4.6.5 == 4.6 == latest
- 4.4.21 == 4.4 == LTS
- 4.5.12 == 4.5

https://hub.docker.com/r/ctsmedia/contao/tags/

Will close the issue in a couple of days if no issues with the update are reported

/cc @ctsmedia/cts-developer
